### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by BrockleyJohn** [MOPS-DanCole/osC-Contributions#1]
This code doesn't do anything. In fact, it doesn't run at all. It's lacking the tags for the beginning and end of php, and anything in between. And a file to put it in. 

You might say "it's empty". 

Oooh, press a colon and you get icons! What does an 8-ball mean? :8ball:

**Comment by MOPS-DanCole** [comment]
John...received your commit.  For some reason it showed up as an issue.  I'll try to add the FAQ files later today...time permitting.

**Comment by BrockleyJohn** [comment]
Actually, I raised it as an issue - to say your text file was missing. Since it wasn't perhaps you should close it. Any idea about the :8ball: ?

If you'd answered the :8ball: I'd close it myself!

**Comment by MOPS-DanCole** [comment]
Interesting...I have no idea about the :8ball: ...maybe I'm behind the :8ball:

**Comment by BrockleyJohn** [comment]
time to close  ;)
